### ISSUE TITLE
Lab 1

### ISSUE THREAD

**Issue by KenanJones** [KenanJones/Maze-cps206#6]
@anthonykulis
This is still kinda messy.
what do you think of the structure?
are the braces and spacing right?

**Comment by anthonykulis** [comment]
Yeah, you have a tabbing problem. When ever you create scope, tab. This is why I suggest putting the opening curly brace on the line of code that starts the scope.

```java
public void example {
     // tab for scope
     if(thisIsAnotherScope){
          // tab for scope
     }
     if(thisIsAnotherScopeToo){
          // tab for scope
          if(thisHasAnotherScope){
               // tab for scope
          }
          for(;;){
               // loops have scope as well
          }
     }
}
```

**Comment by KenanJones** [comment]
Ok, ill work on it.

On Jan 20, 2017, at 11:58 AM, Anthony Kulis <notifications@github.com<mailto:notifications@github.com>> wrote:


Yeah, you have a tabbing problem. When ever you create scope, tab. This is why I suggest putting the opening curly brace on the line of code that starts the scope.

public class Example {
     // tab for scope
     if(thisIsAnotherScope){
          // tab for scope
     }
     if(thisIsAnotherScopeToo){
          // tab for scope
          if(thisHasAnotherScope){
               // tab for scope
          }
          for(;;){
               // loops have scope as well
          }
     }
}

-
